### PR TITLE
Chartboost 8.4.0.0

### PR DESCRIPTION
**Pull request by daniel-barros**
Added safeguard against Chartboost uses on old OS versions.

Chartboost SDK 8.4.0 ignores any method call when running on versions previous to iOS 10. We've made any ad request in this scenario fail in the adapter.

### CODE REVIEW

**Comment by ericleich** [comment]
@arnaumartifont it looks like some commits here were yours. Per the note above, can you respond with `@googlebot I fixed it.`?

**Comment by arnaumartifont** [comment]
@googlebot I fixed it.

**Comment by arnaumartifont** [comment]
@googlebot I fixed it.

**Comment by daniel-barros** [comment]
@googlebot I consent.

**Comment by arnaumartifont** [comment]
@googlebot I consent.

**Comment by arnaumartifont** [comment]
@ericleich all good 👍

**Pull request merged**
