### PR TITLE
Update to Verizon SE v1.14.1

### PR DESCRIPTION
**Pull request by thomas-poland**
This update for SE v1.14.1 is ready to review, thanks!

### CODE REVIEW

**Comment by chlandacastro** [comment]
HI, Native ads are not rendering in this version and the previous version 1.14.0.0.   We are waiting if anyone can check on it.

**Comment by thomas-poland** [comment]
@chlandacastro  Please would you try  the id `ca-app-pub-7866899558273871/9709724822` - this is filling for consistently in both v1.14.0 and v1.14.1 in our adapter test app; if that doesn't work, please could send the verbose log output for that case from your test app ( `VASAds.logLevel` = VASLogLevelVerbose;), thanks!

**Comment by chlandacastro** [comment]
@thomas-poland   Thanks Thomas,  I will need also the App ID to test it, could you send me that?,   the one you sent me is the Unit ID for Native ads,  I will send you the verbose log at the end of the day most likely.

**Comment by chlandacastro** [comment]
Hi Thomas the following is the verbosa log, 
AS-VASConfiguration <1503:1630431420172> Domain "com.verizon.ads.core.config" protected.
2021-08-31 10:37:00.649597-0700 TestApp[88017:1238440] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
2021-08-31 10:37:00.657581-0700 TestApp[88017:1238440]  - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-3212738706492790~5539247190
2021-08-31 10:37:00.665891-0700 TestApp[88017:1238444] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.665898-0700 TestApp[88017:1238446] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.666269-0700 TestApp[88017:1238444] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.666295-0700 TestApp[88017:1238446] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.667467-0700 TestApp[88017:1238444] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.667710-0700 TestApp[88017:1238441] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.670460-0700 TestApp[88017:1238441] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.670595-0700 TestApp[88017:1238441] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2021-08-31 10:37:00.664814-0700 TestApp[88017:1238442]  - <Google>[I-ACS023007] Analytics v.80300000 started
2021-08-31 10:37:00.793838-0700 TestApp[88017:1238442]  - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-08-31 10:37:00.813825-0700 TestApp[88017:1238446]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-08-31 10:37:00.960636-0700 TestApp[88017:1238446]  - <Google>[I-ACS023012] Analytics collection enabled
VAS-VASAds <0:1630431421086> VASSKAdNetworkUtil:initializeWithIABManagedListURL: https://s.yimg.com/an/skadnetwork/v1/skadnetwork-iab-managedlist.json failed with error Error Domain=com.verizon.ads.skadnet.ErrorDomain Code=1 "No valid SKAdNetworkItems were available to process" UserInfo={NSLocalizedDescription=No valid SKAdNetworkItems were available to process}
VAS-VASAds <0:1630431421086> VASSKAdNetworkUtil:initializeWithIABManagedListURL: https://s.yimg.com/an/skadnetwork/v1/skadnetwork-iab-managedlist.json completion with result 2
VAS-VASEnvironmentInfo <0:1630431421086> Usage description string is not available for the feature (NSLocationWhenInUseUsageDescription)
VAS-VASEnvironmentInfo <0:1630431421086> Usage description string is not available for the feature (NSLocationAlwaysUsageDescription)
VAS-VASEnvironmentInfo <0:1630431421086> Suppressing createLocationManager function because a required usage description for either (NSLocationAlwaysUsageDescription) or (NSLocationWhenInUseUsageDescription) was not found in the Info.plist file.
VAS-VASAds <0:1630431421089> Initializing the Verizon Ad SDK
VAS-VASPlugin <0:1630431421089> Prepare called for: <VASVerizonSSPConfigProviderPlugin:0x6000039099e0> name:'Verizon SSP Config Provider', version:'2.8.1-61bae57f', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASConfiguration <0:1630431421089> Domain "com.verizon.ads.verizonssp" protected.
VAS-VASVerizonSSPConfigProvider <0:1630431421089> Loading handshake file.
VAS-VASVerizonSSPConfigProvider <0:1630431421090> Parsing handshake:{"nativeTmax":20000,"vastSkipOffsetMin":7500,"rptFreq":120000,"ver":"1","clientAdTmax":10000,"instlExpDur":3600000,"inlineTmax":10000,"ttl":86400000,"playlistServer":{"name":"orange","baseUrl":"https://ads.nexage.com"},"exTmax":10000,"rptBaseUrl":"https://ads.nexage.com","instlTmax":30000,"vastSkipOffsetMax":16000,"fileAndContentAccessEnabled":false,"handshakeBaseUrl":"https://ads.nexage.com","minInlineRefresh":20000,"rptBatchSize":5,"nativeExpDur":3600000,"serverAdTmax":10000,"fileURLAccessEnabled":false,"nativeConfig":{"typeDefs":{"100":{"name":"inline","components":{"body":{"publisherRequired":0,"advertiserRequired":1},"rating":{"publisherRequired":0,"advertiserRequired":0},"title":{"publisherRequired":1,"advertiserRequired":1},"iconImage":{"publisherRequired":1,"advertiserRequired":1},"callToAction":{"publisherRequired":1,"advertiserRequired":1},"mainImage":{"publisherRequired":0,"advertiserRequired":1},"disclaimer":{"publisherRequired":1,"advertiserRequired":0}}},"101":{"name":"facebook","components":{"title":{"publisherRequired":1,"advertiserRequired":1},"iconImage":{"publisherRequired":1,"advertiserRequired":1},"callToAction":{"publisherRequired":1,"advertiserRequired":1},"disclaimer":{"publisherRequired":1,"advertiserRequired":0},"mainImage":{"publisherRequired":0,"advertiserRequired":1}}}}},"minImpressionViewabilityPercent":0,"overrideAttUnknown":true,"geoIpCheckCacheTtl":604800000,"iabSKAdNetworkIDListUrl":"https://cdn.ssp.yahoo.com/skadnetwork/latest/skadnetwork-iab-managedlist.json","config":"5e365f09fa81dffe82858cf69559026b"}
VAS-VASVerizonSSPConfigProvider <0:1630431421091> Handshake successfully parsed
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASSupportPlugin:0x6000008a75c0> name:'Support', version:'1.15.0-b4d89ea', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASInlinePlacementPlugin:0x6000008a7680> name:'Inline Placement', version:'1.8.0-4c381d7', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASInlineWebAdapterPlugin:0x6000008a77c0> name:'Inline Web Adapter', version:'1.8.0-12aba42', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASInlineWebAdapterPlugin <0:1630431421093> registering the ad - adapter - content filter triplett
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASInterstitialPlacementPlugin:0x6000008a7880> name:'Interstitial Placement', version:'1.8.0-7cb2e29', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASInterstitialWebAdapterPlugin:0x6000008a7a40> name:'Interstitial Web Adapter', version:'1.8.0-2f89bcd', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASInterstitialWebAdapterPlugin <0:1630431421093> Registering the ad - adapter - content filter triplett
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASNativePlacementPlugin:0x6000008a7b00> name:'Native Placement', version:'1.14.0-702b8a0', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASVerizonNativeControllerPlugin:0x6000008a7c80> name:'VASVerizonNativeControllerPlugin', version:'2.15.0-fd079f3', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASNativeVerizonNativeAdapterPlugin:0x600000852f00> name:'Native Verizon Native Adapter', version:'2.9.0-a7e7dc1', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASNativeVerizonNativeAdapterPlugin <0:1630431421093> Registering plugin VASNativeVerizonNativeAdapterPlugin.
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASVASTControllerPlugin:0x60000084f740> name:'VAST Controller', version:'1.10.0-452b875', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASVideoPlayerPlugin:0x600000846e80> name:'VideoPlayer', version:'1.9.0-a7ee015', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASWebControllerPlugin:0x60000087bcc0> name:'Web Controller', version:'1.7.0-1f72b79', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASWebViewPlugin:0x60000087a1c0> name:'WebView', version:'1.10.0-ff94446', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASInterstitialVASTAdapterPlugin:0x60000087b800> name:'Interstitial VAST Adapter', version:'1.8.0-e4a72c8', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASInterstitialVASTAdapterPlugin <0:1630431421093> Registering the ad - adapter - content filter triplett
VAS-VASPlugin <0:1630431421093> Prepare called for: <VASURIExperiencePlugin:0x600003e64910> name:'URI Experience', version:'2.9.0-932602c', author:'Verizon', email:'(null)', website:'(null)', minApiLevel:1
VAS-VASURIExperiencePlugin <0:1630431421093> Registering plugin VASURIExperiencePlugin.
VAS-VASFlurryAnalyticsBootstrap <0:1630431421094> No Flurry Analytics api-key provided.
VAS-VASVerizonSSPConfigProvider <1b0b:1630431421095> Error Domain=com.verizon.ads.vassspconfigprovider.ErrorDomain Code=5 "Handshake already in progress." UserInfo={VASErrorInfoWho=VASVerizonSSPConfigProvider, NSLocalizedDescription=Handshake already in progress.}
VAS-VASAds <5003:1630431421095> An error occurred while updating configuration provider id <(null)>: Error Domain=com.verizon.ads.vassspconfigprovider.ErrorDomain Code=5 "Handshake already in progress." UserInfo={VASErrorInfoWho=VASVerizonSSPConfigProvider, NSLocalizedDescription=Handshake already in progress.}
2021-08-31 10:37:01.096073-0700 TestApp[88017:1237995] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600001d49940> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2021-08-31 10:37:01.118957-0700 TestApp[88017:1237995] {
    GADMediationAdapterChartboost = "<GADAdapterStatus: 0x600001371140; state = Not Ready;No such adapter in the application.>";
    GADMediationAdapterIronSource = "<GADAdapterStatus: 0x600001371170; state = Not Ready;No such adapter in the application.>";
    GADMediationAdapterMyTarget = "<GADAdapterStatus: 0x60000137c3c0; state = Not Ready;No such adapter in the application.>";
    GADMediationAdapterUnity = "<GADAdapterStatus: 0x60000137c030; state = Not Ready;No such adapter in the application.>";
    GADMediationAdapterVerizon = "<GADAdapterStatus: 0x6000013543c0; state = Not Ready;Initialization in progress.>";
    GADMediationAdapterVungle = "<GADAdapterStatus: 0x60000137c330; state = Not Ready;No such adapter in the application.>";
    GADMobileAds = "<GADAdapterStatus: 0x60000137c210; state = Ready>";
}
2021-08-31 10:37:01.254455-0700 TestApp[88017:1237995] WF: === Starting WebFilter logging for process TestApp
2021-08-31 10:37:01.254763-0700 TestApp[88017:1237995] WF: _userSettingsForUser : (null)
2021-08-31 10:37:01.254886-0700 TestApp[88017:1237995] WF: _WebFilterIsActive returning: NO
VAS-VASVerizonSSPConfigProvider <1b0b:1630431421333> Parsing handshake:{"nativeTmax":20000,"vastSkipOffsetMin":7500,"rptFreq":120000,"ver":"1","clientAdTmax":10000,"instlExpDur":3600000,"inlineTmax":10000,"ttl":86400000,"playlistServer":{"name":"orange","baseUrl":"https://ads.nexage.com"},"exTmax":10000,"rptBaseUrl":"https://ads.nexage.com","instlTmax":30000,"vastSkipOffsetMax":16000,"fileAndContentAccessEnabled":false,"handshakeBaseUrl":"https://ads.nexage.com","minInlineRefresh":20000,"rptBatchSize":5,"nativeExpDur":3600000,"serverAdTmax":10000,"fileURLAccessEnabled":false,"nativeConfig":{"typeDefs":{"100":{"name":"inline","components":{"body":{"publisherRequired":0,"advertiserRequired":1},"rating":{"publisherRequired":0,"advertiserRequired":0},"title":{"publisherRequired":1,"advertiserRequired":1},"iconImage":{"publisherRequired":1,"advertiserRequired":1},"callToAction":{"publisherRequired":1,"advertiserRequired":1},"mainImage":{"publisherRequired":0,"advertiserRequired":1},"disclaimer":{"publisherRequired":1,"advertiserRequired":0}}},"101":{"name":"facebook","components":{"title":{"publisherRequired":1,"advertiserRequired":1},"iconImage":{"publisherRequired":1,"advertiserRequired":1},"callToAction":{"publisherRequired":1,"advertiserRequired":1},"disclaimer":{"publisherRequired":1,"advertiserRequired":0},"mainImage":{"publisherRequired":0,"advertiserRequired":1}}}}},"minImpressionViewabilityPercent":0,"overrideAttUnknown":true,"geoIpCheckCacheTtl":604800000,"iabSKAdNetworkIDListUrl":"https://cdn.ssp.yahoo.com/skadnetwork/latest/skadnetwork-iab-managedlist.json","config":"5e365f09fa81dffe82858cf69559026b"}
VAS-VASVerizonSSPConfigProvider <1b0b:1630431421333> Handshake successfully parsed
VAS-VASVerizonSSPConfigProvider <1b0b:1630431421334> Saving handshake file.
2021-08-31 10:37:04.668472-0700 TestApp[88017:1237995] <Google> To get test ads on this device, set: 
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ kGADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ kGADSimulatorID ]
2021-08-31 10:37:04.701826-0700 TestApp[88017:1238390] <Google> <Google:HTML> A valid SKAdNetworkIdentifier for Google (cstr6suwn9.skadnetwork) is missing from Info.plist. See [Enable SKAdNetwork to track conversions] (https://googlemobileadssdk.page.link/enable-skadnetwork)
VAS-VASNativeAdFactory <0:1630431425694> loading an ad with delegate: <GADMAdapterVerizonNativeAd: 0x6000013abe70>
VAS-VASNativeAdFactory <1703:1630431425694> Attempting load Native Ad from cache with delegate: <GADMAdapterVerizonNativeAd: 0x6000013abe70>
VAS-VASNativeAdFactory <1703:1630431425694> No Native Ad in cache
VAS-VASVerizonSSPWaterfallProvider <5003:1630431425777> Playlist response does not match requested version
VAS-VASAdRequest <2803:1630431425777> Waterfall Provider reported error: Error Domain=com.verizon.ads.core.ErrorDomain Code=9 "Invalid waterfall JSON data." UserInfo={VASErrorInfoWho=VASVerizonSSPWaterfallProvider, NSLocalizedDescription=Invalid waterfall JSON data.}
VAS-VASNativeAdFactory <2803:1630431425777> Failed to load ad with error: Error Domain=com.verizon.ads.core.ErrorDomain Code=9 "Invalid waterfall JSON data." UserInfo={VASErrorInfoWho=VASVerizonSSPWaterfallProvider, NSLocalizedDescription=Invalid waterfall JSON data.}

**Comment by thomas-poland** [comment]
@chlandacastro  Here's the App ID we are using with the above placement: `ca-app-pub-7866899558273871~5689279345`

**Comment by thomas-poland** [comment]
@chlandacastro Based on the log, it looks like the existing native test placement reference by your test app hasn't yet been updated for v1.14 yet, if the new placement noted above works for you, one option is to just update your Test app to point to that on your App's dashboard.

**Comment by chlandacastro** [comment]
@thomas-poland   Thanks, rewarded ads are now rendering for both versions, 1.14.0 and 1.14.1.

**Comment by chlandacastro** [comment]
@thomas-poland.   It is rendering native ads now using the App ID provided, 
Thanks,

**Comment by thomas-poland** [comment]
@chlandacastro  Inn `80330ec` I fixed the conflict in CHANELOG.md (rebased), no other changes

**Comment by chlandacastro** [comment]
Hi Thomas could you rebase this PR, since we have updated the code.  Also, could you provide with the Unit ID for future testing since our native ad Unit ID is not working.    We need the Unit ID for banners, rewarded and interstitial we already have the unit Id for Native and also the App ID.    We need to have all of them from the same App ID, that is why we need the others unit ids,  Thanks.

**Comment by thomas-poland** [comment]
@chlandacastro ok - rebased - here are the ad unit IDs we are using in our test app:

app ID: `ca-app-pub-7866899558273871`

inline:  
AdMob slotname: `ca-app-pub-7866899558273871/5280158719`  dcn (SSP id): `8a809417014d4ce79fa8059b42390154` Vz placement id: `240331`

interstitial:
AdMob slotname: `ca-app-pub-7866899558273871/4242409215` dcn (SSP id): `8a809417014d4ce79fa8059b42390154` Vz placement id: `240332`

native:
AdMob slotname: `ca-app-pub-7866899558273871/9709724822` dcn (SSP id): `8a809417014d4ce79fa8059b42390154` Vz placement id: `240520`

**Comment by chlandacastro** [comment]
thanks,  what about rewarded unit id?

**Comment by thomas-poland** [comment]
@chlandacastro for Rewarded video: `ca-app-pub-7866899558273871/7095169776` `8a809417014d4ce79fa8059b42390154` `240335`

**Pull request merged**
