### PR TITLE
Delete the isReady check condition.

### PR DESCRIPTION
**Pull request by Mintegral-Lee**
Delete the isReady check condition

### CODE REVIEW

**Comment by Mintegral-Lee** [comment]
For admob, Mintegral Ad SDk will no longer check isReady, please review and merge.
Thanks!

**Comment by Mintegral-Lee** [comment]
@thanvirm Please review this pull request,thanks!

For admob, Mintegral Ad SDk will no longer check isReady, please review and merge.

**Comment by thanvirm** [comment]
> @thanvirm Please review this pull request,thanks!
> 
> For admob, Mintegral Ad SDk will no longer check isReady, please review and merge.

Sorry for the delay. Will review this PR as soon as possible.

**Comment by thanvirm** [comment]
If isReady check is removed, what will happen if the ad is presented before it is ready?

**Comment by Mintegral-Lee** [comment]
> If isReady check is removed, what will happen if the ad is presented before it is ready?

@thanvirm The show method will check whether there are ads that can be displayed.

**Comment by thanvirm** [comment]
> > If isReady check is removed, what will happen if the ad is presented before it is ready?
> 
> @thanvirm The show method will check whether there are ads that can be displayed.

Thanks for the clarification. The change looks good to me. Could you update the [CHANGELOG.md](https://github.com/googleads/googleads-mobile-ios-mediation/blob/main/adapters/Mintegral/CHANGELOG.md?plain=1) file with a description of the changes under the heading "#### Next version"? Thanks!

**Comment by Mintegral-Lee** [comment]
> > > If isReady check is removed, what will happen if the ad is presented before it is ready?
> > 
> > 
> > @thanvirm The show method will check whether there are ads that can be displayed.
> 
> Thanks for the clarification. The change looks good to me. Could you update the [CHANGELOG.md](https://github.com/googleads/googleads-mobile-ios-mediation/blob/main/adapters/Mintegral/CHANGELOG.md?plain=1) file with a description of the changes under the heading "#### Next version"? Thanks!

@thanvirm  ok,I have added.

**Comment by Mintegral-Lee** [comment]
> > > If isReady check is removed, what will happen if the ad is presented before it is ready?
> > 
> > 
> > @thanvirm The show method will check whether there are ads that can be displayed.
> 
> Thanks for the clarification. The change looks good to me. Could you update the [CHANGELOG.md](https://github.com/googleads/googleads-mobile-ios-mediation/blob/main/adapters/Mintegral/CHANGELOG.md?plain=1) file with a description of the changes under the heading "#### Next version"? Thanks!

@thanvirm  ok,I have added.

**Comment by thanvirm** [comment]
Hi,

Thank you for your change. The change looks good to me.

But, unfortunately, the change is causing the existing unit tests for Mintegral adapter to fail. Could you please fix the unit tests? [Here](https://github.com/googleads/googleads-mobile-ios-mediation/blob/main/AdapterUnitTests/README.md) are instructions for how to run the unit tests. Thanks!

**Comment by thanvirm** [comment]
Thank you for the changes. The pull request looks good now. I will import this into our internal codebase. GitHub code will get updated after I do that. Thanks!

**Pull request merged**
