### PR TITLE
fix nil object in images array crash

### PR DESCRIPTION
**Pull request by popic28**
Hello all,

This PR adds a nil check after creating the image URL's.
I've reported the crash in issue #13 

Thanks, and let me know if there's anything else to do from my side.

### CODE REVIEW

**Comment by popic28** [comment]
signed the CLA

**Comment by ericleich** [comment]
Thanks for the PR. We'll take a closer look tomorrow.

Initial thoughts:
1) Are you able to reproduce locally? If so, can you share repro steps? I'm curious what the string is that would cause the URL to be nil. Nil check addresses the crash but it may be a larger problem that certain image assets aren't returned.
2) The PR itself seems to be missing a closing )

**Comment by ericleich** [comment]
Turns out we are already working with MoPub on getting to the bottom of this issue. Current diagnosis is that the URLs come in malformed, but we can't reproduce.

We aren't sure that nilling out is the right solution, so we don't plan to accept this PR at this moment. If you think this change makes sense for you right now in your own app, feel free to make a build for yourself with these changes. The xcodeproj for the MoPub adapter should be set up to let you run the Fat adapter target after dropping in the Google Mobile Ads and MoPub libraries in [this directory](https://github.com/googleads/googleads-mobile-ios-mediation/tree/master/adapters/MoPub/Library).

**Comment by ericleich** [comment]
Having said all that, if the issue is indeed malformed urls, the nil check wouldn't even prevent crashes...

**Comment by sbagadi** [comment]
Fixed by https://github.com/googleads/googleads-mobile-ios-mediation/pull/19

**Pull request closed without merging**
