### PR TITLE
AdColony 3.0.6.0 Adapter #4

### PR DESCRIPTION
**Pull request by shawnkc**

### CODE REVIEW

**Comment by RedBrogdon** [comment]
Shawn, are you covered under the corporate CLA for Opera Mediaworks? When signing the CLA, companies designate a Google group to which they add the emails of each of their coders (these need to be the email addresses registered with Github). It appears that you're not included in that group.

**Comment by RedBrogdon** [comment]
Rerunning CLA check.

**Comment by RedBrogdon** [comment]
Running CLA check once more.

**Comment by ericleich** [comment]
Test CLA

**Comment by RedBrogdon** [comment]
Rerunning CLA bot.

**Pull request merged**
