### PR TITLE
Update nend adapter to version 5.1.1.0

### PR DESCRIPTION
**Pull request by fan-c-yu**

### CODE REVIEW

**Comment by stowy** [comment]
Hi @fan-c-yu - has Nend changed it's policy or supported ad sizes?

**Comment by fan-c-yu** [comment]
Hi @stowy 
> has Nend changed it's policy or supported ad sizes?

No.

And we will update nend adapter version to 5.1.1.0 on this pull request later. 
Please wait for a moment.

**Comment by fan-c-yu** [comment]
Hello @stowy 
I updated nend adapter version to 5.1.1.0 and fixed the conflicts problem by merge the master branch.
Then I find this #112.

**Comment by stowy** [comment]
@fan-c-yu thanks we will look to resolve that. Did you notice that the [new code restricts nend ads to the following sizes](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Nend/NendAdapter/GADMAdapterNend.m#L25):

```objc
  NSArray *potentials = @[
    NSValueFromGADAdSize(kGADAdSizeBanner),
    NSValueFromGADAdSize(kGADAdSizeLargeBanner),
    NSValueFromGADAdSize(kGADAdSizeMediumRectangle),
    NSValueFromGADAdSize(kGADAdSizeLeaderboard),
  ];
```

**Comment by fan-c-yu** [comment]
@stowy 
Yes, we noticed the restrictions and have no problem with that.
We just don not want to check the size when received the ad.

**Comment by stowy** [comment]
Ok sure no problem.

**Pull request merged**
