### PR TITLE
Update banner size check for nend adapter

### PR DESCRIPTION
**Pull request by fan-c-yu**

### CODE REVIEW

**Comment by fan-c-yu** [comment]
I signed it!

**Comment by stowy** [comment]
@fan-c-yu can you explain the rationale behind this change?

**Comment by fan-c-yu** [comment]
@stowy This is for smart banner. Ad which is smaller than placement size can be displayed.
#105

**Comment by fan-c-yu** [comment]
We are rethinking about the change, withdraw once.

**Pull request closed without merging**
